### ISSUE TITLE
How to transfer config/data from vanilla kodi 

### ISSUE THREAD

**Issue by qu4542** [fandangos/JRE-Kodi-Android#3]
Hey is it possible to transfer the configs and database from a vanilla kodi (shield tv) to this custom version without loosing its custom features?

**Comment by fandangos** [comment]
It depends how many addons and what settings you use but should be fine.
Just copy your user profile folder from /sdcard/Android/data/org.xbmc.kodi/files/.kodi/ to this one, looking at the package name and you should be good to go.
