### ISSUE TITLE
JRE does not work with Maven's Kodi 20 builds

### ISSUE THREAD

**Issue by Juca1107** [fandangos/JRE-Kodi-Android#4]
After installing the JRE add-on and then selecting in Kodinerds 20 show blu-ray menu writes "could not find JRE"
In Kodinerds 19 everything works
https://www.kodinerds.net/index.php/Thread/69428-Maven-s-Kodi-Builds-f%C3%BCr-Android/?postID=586409#post586409
https://repo.kodinerds.net/index.php?action=list&scope=cat&item=Binary%20(armeabi-v7a)

**Comment by fandangos** [comment]
I have updated my Kodi build with the latest changes of Kodi Omega, which includes Dolby Vision and added the patches necessary for complete bluray playback.

I have updaded the JRE addon necessary to run it. 

Only ARM (32bits) version for now.

**Comment by Juca1107** [comment]
The JRE downloaded from https://github.com/fandangos/JRE-Kodi-Android/releases/download/Omega/script.service.jre.zip installs on Maven's Kodinerds Nexus, but the Blu-ray menu does not launch. Is it possible to make a JRE for Nexus?

**Comment by fandangos** [comment]
The addon is not meant to be used with Maven's Kodinerds builds. 

You need to get the the ARM or AARCH64 version from here:
https://github.com/fandangos/Kodi-HDR-Edition/releases

and the addon updated for it here:
https://github.com/fandangos/JRE-Kodi-Android/releases

I have no affiliation, work, or support other builds, you have to use the addon with the provided apk.
