### ISSUE TITLE
JRE does not work with Maven's Kodi 20 builds

### ISSUE THREAD

**Issue by Juca1107** [fandangos/JRE-Kodi-Android#5]
The JRE downloaded from https://github.com/fandangos/JRE-Kodi-Android/releases/download/Omega/script.service.jre.zip installs on Maven's Kodinerds Nexus, but the Blu-ray menu does not launch. Is it possible to make a JRE for Kodi Nexus?

**Comment by Juca1107** [comment]
Kodi Omega crashes when launching Blu-ray menu. Works stably with the menu only Kodi Matrix with an old version of JRE.

**Comment by fandangos** [comment]
The addon is not meant to be used with Maven's Kodinerds builds. 

You need to get the the ARM or AARCH64 version from here:
https://github.com/fandangos/Kodi-HDR-Edition/releases

and the addon updated for it here:
https://github.com/fandangos/JRE-Kodi-Android/releases

I have no affiliation, work, or support other builds, you have to use the addon with the provided apk.

----------------------------

I have tested this addon with Nvidia Shield TV PRO and other users on Kodi's forum reported success, no crashes.
