### ISSUE TITLE
can't play the full menu of the ISO disc

### ISSUE THREAD

**Issue by ne7erland** [fandangos/JRE-Kodi-Android#6]
Hello, after installing your [kodiapp-arm64-v8a-release-v1.21.apk](https://github.com/fandangos/Kodi-HDR-Edition/releases/download/1.21/kodiapp-arm64-v8a-release-v1.21.apk), install this([script.service.jre-aarch64-v1.2.zip](https://github.com/fandangos/JRE-Kodi-Android/releases/download/1.2-aarch64/script.service.jre-aarch64-v1.2.zip)), still can't play the full menu of the ISO disc, as soon as I open it crashes, I can only play the simple menu

**Comment by fandangos** [comment]
You are the first one ever to report a crash.

What device are you using?

Can you post a debug log?

**Comment by fandangos** [comment]
https://forum.kodi.tv/showthread.php?tid=371573

This seems to be main Kodi issue and it seems a fix it's on the way.
If the fix is merged into master branch (nexus) I'll update my build.

**Comment by Ser-vie** [comment]
Has the problem not been solved in Kodi in the meantime?

**Comment by fandangos** [comment]
What problem?
Many have tested the addon + the build without issues.

I can only test it in the Nvidia Shield and it does work.
If your device is 32bit and you install arm64 it won't work.

**Comment by Ser-vie** [comment]
No more issue.
The issue here is solved, after all.
Isn't it better to close this issue then?
